<?php

?>

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Calculatrice</title>
    </head>
    <body>
        <h1>Calculatrice</h1>
        <form action="index.php" method="POST">
            <label for="number-one">Nombre 1</label>
            <input type="number" name="number-one" id="number-one" required>
            
            <label for="number-two">Nombre 2</label>
            <input type="number" name="number-two" id="number-two">
            
            <select id="operation" name="operation">
                <option value="">Choisissez une opération</option>
                <option value="addition">Addition</option>
                <option value="soustraction">Soustraction</option>
                <option value="multiplication">Multiplication</option>
                <option value="division">Division</option>
                <option value="puissance">Puissance</option>
                <option value="factorielle">Factorielle</option>
            </select>
            
            <select id="surface" name="surface">
                <option value="">Choisissez un calcul de surface</option>
                <option value="rectangle">Rectangle</option>
                <option value="triangle rectangle">Triangle rectangle</option>
                <option value="triangle">Triangle</option>
                <option value="cercle">Cercle</option>
            </select>
            
            <input name="submit" id="submit" type="submit" value="Calculer">
        </form>
    </body>
</html>